### ISSUE TITLE
Calling /api/sasurl - 500 Error

### ISSUE THREAD

**Issue by nor0x** [Microsoft/Appsample-Photosharing#33]
I setup the project following the instructions in GettingStarted.md. Everything is working fine, except the `sasurl` endpoint, which returns  a 500 response code with the following body
`{
  "message": "An error has occurred."
}`

The other API endpoints are working fine. Anything I am missing out? Any help is appreciated.

**Comment by EricAtMSFT** [comment]
Please double check your Azure Storeage configs and make sure your Azure storage name and key are correct. See this file: 

https://github.com/Microsoft/Appsample-Photosharing/blob/master/PhotoSharingApp/PhotoSharingApp.AppService.Shared/Context/EnvironmentDefinition.cs

Your StorageAccessKey should be a long string that ends with a "==". Can you check?

**Comment by nor0x** [comment]
Thank you for the answer.
StorageAccessKey and StorageAccountName should be set correctly. I tried both keys created by Azure.
<img width="863" alt="screenshot029348" src="https://cloud.githubusercontent.com/assets/3210391/17905365/0c3c6c22-6973-11e6-83d6-fca6004c1438.png">

**Comment by nor0x** [comment]
I found the error! I was using the latest version of the WindowsAzure.Storage NuGet package (7.2.0) - after a downgrade to 7.1.2 everything is working fine.
Thank you!
my bad - closed
