### ISSUE TITLE
DesignTime error "ServiceLocationProvider must be set"

### ISSUE THREAD

**Issue by ToddBonnewell** [Microsoft/Appsample-Photosharing#35]
Following the documentation I notice I cannot view Design Time data. When I open LeaderboardsPage.xaml I am not seeing the data, just a ListView of categories. In the Error List in Visual Studio it reports:

ServiceLocationProvider must be set

![image](https://cloud.githubusercontent.com/assets/14977667/18817981/85af5114-833b-11e6-9e73-8d64fca0c6e6.png)

![image](https://cloud.githubusercontent.com/assets/14977667/18817991/9a2eadc4-833b-11e6-9316-c987a8301702.png)

How can I get some DesignTime data working? Thanks!

**Comment by ToddBonnewell** [comment]
9 days. Not one comment?

**Comment by AstumppMSFT** [comment]
Hi @ToddBonnewell,
sorry for the delay on this. We might have broken this with one of our latest check-ins. Good finding, here's a solution that brings back the configuration of the dependency container at design time:

Add this class to the PhotoSharing.Universal project:
```csharp
namespace PhotoSharingApp.Universal.Unity
{
    public class DesignTimeInitializer
    {
        public DesignTimeInitializer()
        {
            if (DesignMode.DesignModeEnabled && UnityBootstrapper.Container == null)
            {
                UnityBootstrapper.Init();
                UnityBootstrapper.ConfigureRegistries();
            }
        }
    }
}
```

And in Styles.xaml, add following initialization at the beginning of the file:
```xml
<unity:DesignTimeInitializer x:Key="DesignTimeInitializer"/>
```

Once you've configured Unity to load up at design time, it will populate data from the PhotoDummyService, if you're in Debug mode and have the DUMMY_SERVICE compiler directive set.

![image](https://cloud.githubusercontent.com/assets/15805663/19097319/aa7273ae-8a58-11e6-88ab-e3ededa74808.png)

Let me know if you have any questions.

**Comment by ToddBonnewell** [comment]
Thanks!!!!
