### ISSUE TITLE
Server Error in App Service

### ISSUE THREAD

**Issue by scout208** [Microsoft/Appsample-Photosharing#42]
I followed the Getting Started directions step-by-step, and when I published my app and opened the app service url in my browser, I got a server error.

The actual error is `Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

Here's a screenshot of the error with its trace:
![server error](https://cloud.githubusercontent.com/assets/9426329/26174032/951149ce-3b13-11e7-8aef-aa086648fa78.PNG)

# Update:
The App Service works fine when I debug it locally. This error is only occurring when it is running on Azure.

**Comment by scout208** [comment]
I tried again today and everything is working fine. I didn't change any of the published code. I guess it just took some time to publish and I was maybe accessing it to soon?

**Comment by EricAtMSFT** [comment]
Glad we could help. :)

**Comment by scout208** [comment]
@EricAtMSFT I'm glad that it is working, but I still don't understand how this happened. Was there a problem with Azure when I was trying to access it or did it take longer for the code to finish deploying and I was trying to access it to soon? Do you have any idea?

**Comment by EricAtMSFT** [comment]
I've seen this weirdness in Azure now and then. For me, I get the best results when I publish an app by checking the "Remove additional files at destination" checkbox. That guarantees you'll get a clean environment. Glad it fixed itself. Have fun with SnapGold!
